<script language="javascript" type="text/javascript"> 
  dayName = new Array ("Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy") 
  monName = new Array ("1","2","3","4","5","6","7","8","9","10","11","12") 
  now = new Date ;
    gio = now.getHours();

if (gio == 22, gio == 12) {
  document.write ("<style>body {background: #171c25!important} #leftmenu ul li {color: #ededed!important} #leftmenu ul li:hover{color: #000!important} #leftmenu h9 {color: #e6e6e6!important} #ban-be-right ul li {color: #e6e6e6!important} #ban-be-right ul li:hover {color: #000!important} a:link, a:visited {color: #4976d1} .post {background: rgba(0,0,0,.2)!important; border: none!important} .snippets {color: #e6e6e6!important} .post-body {color: #e6e6e6!important} h1.post-title, .chu-de {color: #e6e6e6!important} .post-status, .tkn-post-contact {background: rgba(0,0,0,.2)!important} .tkn-title-post {border: 1px solid #313438!important; background: #313438!important; color: #e6e6e6!important} .sttcontact {color: #e2e2e2!important; background: #313438!important} .sidebar h2, .sidebar h3 {color: #e6e6e6!important; background: rgba(0,0,0,.2)!important} #sidebar .widget-content, #sidebar2 .widget-content {background: rgba(0,0,0,.2)!important} .thong-tin h1, .thong_tin ul li p, #sidebar .widget-content, #sidebar2 .widget-content, i.icon-fb, subs {color: #e6e6e6!important} .congcupost a, .congcupost a, .dropdown-link, .thich-mau-toi {color: #898f9c!important} .sidebar .popular-posts ul li{border: 1px solid rgba(0,0,0,.2)!important} .ttthem .tieude {color: #e6e6e6!important} .img-thumbnail, .hoveranh .ttthem {border: 1px solid #3e4247!important}  #comments {background: rgba(0,0,0,.2)!important; border: 1px solid rgba(0,0,0,.2)!important }  .comment_body {background: rgba(0,0,0,.2)!important} .comment_body p, .comment_reply {color: #e6e6e6!important} .react{border-bottom: 1px solid #3e4247!important}  </style>")
}
if (gio == 24, gio == 1) {
  document.write ("<style>body {background: #171c25!important} #leftmenu ul li {color: #ededed!important} #leftmenu ul li:hover{color: #000!important} #leftmenu h9 {color: #e6e6e6!important} #ban-be-right ul li {color: #e6e6e6!important} #ban-be-right ul li:hover {color: #000!important} a:link, a:visited {color: #4976d1} .post {background: rgba(0,0,0,.2)!important; border: none!important} .snippets {color: #e6e6e6!important} .post-body {color: #e6e6e6!important} h1.post-title, .chu-de {color: #e6e6e6!important} .post-status, .tkn-post-contact {background: rgba(0,0,0,.2)!important} .tkn-title-post {border: 1px solid #313438!important; background: #313438!important; color: #e6e6e6!important} .sttcontact {color: #e2e2e2!important; background: #313438!important} .sidebar h2, .sidebar h3 {color: #e6e6e6!important; background: rgba(0,0,0,.2)!important} #sidebar .widget-content, #sidebar2 .widget-content {background: rgba(0,0,0,.2)!important} .thong-tin h1, .thong_tin ul li p, #sidebar .widget-content, #sidebar2 .widget-content, i.icon-fb, subs {color: #e6e6e6!important} .congcupost a, .congcupost a, .dropdown-link, .thich-mau-toi {color: #898f9c!important} .sidebar .popular-posts ul li{border: 1px solid rgba(0,0,0,.2)!important} .ttthem .tieude {color: #e6e6e6!important} .img-thumbnail, .hoveranh .ttthem {border: 1px solid #3e4247!important}  #comments {background: rgba(0,0,0,.2)!important; border: 1px solid rgba(0,0,0,.2)!important }  .comment_body {background: rgba(0,0,0,.2)!important} .comment_body p, .comment_reply {color: #e6e6e6!important} .react{border-bottom: 1px solid #3e4247!important}  </style>")
}
if ( gio == 2, gio == 3) {
  document.write ("<style>body {background: #171c25!important} #leftmenu ul li {color: #ededed!important} #leftmenu ul li:hover{color: #000!important} #leftmenu h9 {color: #e6e6e6!important} #ban-be-right ul li {color: #e6e6e6!important} #ban-be-right ul li:hover {color: #000!important} a:link, a:visited {color: #4976d1} .post {background: rgba(0,0,0,.2)!important; border: none!important} .snippets {color: #e6e6e6!important} .post-body {color: #e6e6e6!important} h1.post-title, .chu-de {color: #e6e6e6!important} .post-status, .tkn-post-contact {background: rgba(0,0,0,.2)!important} .tkn-title-post {border: 1px solid #313438!important; background: #313438!important; color: #e6e6e6!important} .sttcontact {color: #e2e2e2!important; background: #313438!important} .sidebar h2, .sidebar h3 {color: #e6e6e6!important; background: rgba(0,0,0,.2)!important} #sidebar .widget-content, #sidebar2 .widget-content {background: rgba(0,0,0,.2)!important} .thong-tin h1, .thong_tin ul li p, #sidebar .widget-content, #sidebar2 .widget-content, i.icon-fb, subs {color: #e6e6e6!important} .congcupost a, .congcupost a, .dropdown-link, .thich-mau-toi {color: #898f9c!important} .sidebar .popular-posts ul li{border: 1px solid rgba(0,0,0,.2)!important} .ttthem .tieude {color: #e6e6e6!important} .img-thumbnail, .hoveranh .ttthem {border: 1px solid #3e4247!important}  #comments {background: rgba(0,0,0,.2)!important; border: 1px solid rgba(0,0,0,.2)!important }  .comment_body {background: rgba(0,0,0,.2)!important} .comment_body p, .comment_reply {color: #e6e6e6!important} .react{border-bottom: 1px solid #3e4247!important}  </style>")
}
</script>